//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudErpV1Entities : DbContext
    {
        public CloudErpV1Entities()
            : base("name=CloudErpV1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAccountControl> tblAccountControl { get; set; }
        public virtual DbSet<tblAccountHead> tblAccountHead { get; set; }
        public virtual DbSet<tblAccountSubControl> tblAccountSubControl { get; set; }
        public virtual DbSet<tblBranchType> tblBranchType { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblCustomer> tblCustomer { get; set; }
        public virtual DbSet<tblCustomerInvoice> tblCustomerInvoice { get; set; }
        public virtual DbSet<tblCustomerInvoiceDetail> tblCustomerInvoiceDetail { get; set; }
        public virtual DbSet<tblCustomerPayment> tblCustomerPayment { get; set; }
        public virtual DbSet<tblFinancialYear> tblFinancialYear { get; set; }
        public virtual DbSet<tblPayroll> tblPayroll { get; set; }
        public virtual DbSet<tblStock> tblStock { get; set; }
        public virtual DbSet<tblSupplier> tblSupplier { get; set; }
        public virtual DbSet<tblSupplierInvoice> tblSupplierInvoice { get; set; }
        public virtual DbSet<tblSupplierInvoiceDetail> tblSupplierInvoiceDetail { get; set; }
        public virtual DbSet<tblSupplierPayment> tblSupplierPayment { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserType> tblUserTypes { get; set; }
        public virtual DbSet<tblCompany> tblCompanies { get; set; }
        public virtual DbSet<tblEmployee> tblEmployees { get; set; }
        public virtual DbSet<tblBranch> tblBranches { get; set; }
    }
}
